/* Load settings */
async function getSettings() {
  const s = await api('get_settings');
  if (!s) return false;
  const hk = document.getElementById('s-hotkey');
  const gif = document.getElementById('s-gif');
  const as = document.getElementById('s-auto-start');
  const ss = document.getElementById('s-silent-start');
  if (hk && s.hotkey) hk.value = s.hotkey;
  const hsam = document.getElementById('s-hotkey-show-at-mouse');
  if (hsam) hsam.checked = s.hotkey_show_at_mouse === true;
  if (gif) gif.checked = s.auto_play_gif !== false;
  const hp = document.getElementById('s-hover-play');
  if (hp) hp.checked = s.hover_to_play === true;
  const to = document.getElementById('s-try-original');
  if (to) to.checked = s.try_original_image === true;  // DeepSeek V4 Flash
  const cm = document.getElementById('s-copy-mode');
  if (cm) cm.value = String(s.copy_resize_mode ?? 1);
  if (as) as.checked = s.auto_start === true;
  if (ss) ss.checked = s.silent_start === true;
  const unc = document.getElementById('s-show-uncategorized');
  if (unc) unc.checked = s.show_uncategorized !== false;
  const rec = document.getElementById('s-record-recent');
  if (rec) rec.checked = s.record_recent_use !== false;
  const ssa = document.getElementById('s-show-startup-anim');
  if (ssa) ssa.checked = s.show_startup_animation !== false;
  toggleSilentStart();
  const ff = document.getElementById('s-sync-fetch');
  const sa = document.getElementById('s-sync-auto');
  const st = document.getElementById('s-sync-type');
  if (ff) ff.checked = s.sync_auto_fetch_index === true;
  if (sa) sa.checked = s.sync_auto_sync === true;
  if (st) { st.value = s.sync_type || ''; toggleSyncType(); }
  document.getElementById('s-ftp-host').value = s.ftp_host || '';
  document.getElementById('s-ftp-port').value = s.ftp_port || 21;
  document.getElementById('s-ftp-user').value = s.ftp_user || '';
  document.getElementById('s-ftp-pass').value = s.ftp_password || '';
  document.getElementById('s-ftp-path').value = s.ftp_path || '/';
  document.getElementById('s3-endpoint').value = s.s3_endpoint || '';
  const s3Addr = document.getElementById('s3-addressing-style');
  if (s3Addr) s3Addr.value = s.s3_addressing_style || 'virtual';
  const s3Sig = document.getElementById('s3-signature-version');
  if (s3Sig) s3Sig.value = s.s3_signature_version || 's3';
  document.getElementById('s3-region').value = s.s3_region || '';
  document.getElementById('s3-bucket').value = s.s3_bucket || '';
  document.getElementById('s3-access-key').value = s.s3_access_key || '';
  document.getElementById('s3-secret-key').value = s.s3_secret_key || '';
  document.getElementById('s3-path').value = s.s3_path || '';
  document.getElementById('r2-account-id').value = s.r2_account_id || '';
  document.getElementById('r2-access-key-id').value = s.r2_access_key_id || '';
  document.getElementById('r2-secret-access-key').value = s.r2_secret_access_key || '';
  document.getElementById('r2-bucket').value = s.r2_bucket || '';
  document.getElementById('r2-path').value = s.r2_path || '';
  document.getElementById('wd-url').value = s.webdav_url || '';
  document.getElementById('wd-user').value = s.webdav_user || '';
  document.getElementById('wd-pass').value = s.webdav_password || '';
  document.getElementById('wd-path').value = s.webdav_path || '';
  const kr = document.getElementById('s-delete-remote');
  const rl = document.getElementById('s-remove-local');
  const hw = document.getElementById('s-hide-upload-warn');
  if (kr) kr.checked = s.sync_delete_remote === true;
  if (rl) rl.checked = s.sync_remove_local === true;
  if (hw) hw.checked = s.sync_hide_upload_warning === true;
  const up = document.getElementById('s-show-up-progress');
  const ud = document.getElementById('s-show-up-done');
  const dp = document.getElementById('s-show-dl-progress');
  const dd = document.getElementById('s-show-dl-done');
  if (up) up.checked = s.show_upload_progress !== false;
  if (ud) ud.checked = s.show_upload_done !== false;
  if (dp) dp.checked = s.show_download_progress !== false;
  if (dd) dd.checked = s.show_download_done !== false;
  const lport = document.getElementById('s-lan-port');
  if (lport) lport.value = s.lan_port || 17852;
  const lsec = document.getElementById('s-lan-secret');
  if (lsec) lsec.value = s.lan_secret || '';
  const tgtd = document.getElementById('s-tg-tdata');
  if (tgtd && s.tg_tdata_path) tgtd.value = s.tg_tdata_path;
  checkConnectivity();  // DeepSeek V4 Flash
  loadStorageInfo();
  refreshLanStatus();
  _settingsDirty = false;
  return true;
}
